version: '3.7'

services:
  crud.usuarios:
    image: ${DOCKER_REGISTRY-}crud
    container_name: crud-app
    build:
      context: .
      dockerfile: Crud/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:5000
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "5000:5000"
    networks:
      - globalnet

  dockersqlserver:
    image: spakov/mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: sql-server-linux
    restart: always
    ports:
      - "1435:1433"
    networks:
      - globalnet

networks:
  globalnet: {}